[0.246s] Invoking command in '/home/valtec/aether/aether_ws/build/aether_interfaces': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/home/valtec/aether/aether_ws/install/aether_gcs_ui:/home/valtec/aether/aether_ws/install/aether_gcs_backend:/opt/ros/humble VIRTUAL_ENV_PROMPT=(.venv) /usr/bin/cmake /home/valtec/aether/aether_ws/src/aether_interfaces -DCMAKE_INSTALL_PREFIX=/home/valtec/aether/aether_ws/install/aether_interfaces
[0.253s] -- Found ament_cmake: 1.3.12 (/opt/ros/humble/share/ament_cmake/cmake)
[0.335s] -- Found rosidl_default_generators: 1.2.0 (/opt/ros/humble/share/rosidl_default_generators/cmake)
[0.337s] -- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
[0.339s] -- Found rosidl_adapter: 3.1.7 (/opt/ros/humble/share/rosidl_adapter/cmake)
[0.358s] -- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
[0.429s] [31mCMake Error at /opt/ros/humble/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:59 (message):
[0.429s]   execute_process(/home/valtec/aether/.venv/bin/python3 -m rosidl_adapter
[0.429s]   --package-name aether_interfaces --arguments-file
[0.429s]   /home/valtec/aether/aether_ws/build/aether_interfaces/rosidl_adapter__arguments__aether_interfaces.json
[0.429s]   --output-dir
[0.429s]   /home/valtec/aether/aether_ws/build/aether_interfaces/rosidl_adapter/aether_interfaces
[0.429s]   --output-file
[0.429s]   /home/valtec/aether/aether_ws/build/aether_interfaces/rosidl_adapter/aether_interfaces.idls)
[0.429s]   returned error code 1:
[0.429s] 
[0.429s]   Traceback (most recent call last):
[0.430s] 
[0.430s]     File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[0.430s]       return _run_code(code, main_globals, None,
[0.430s]     File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[0.430s]       exec(code, run_globals)
[0.430s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__main__.py", line 19, in <module>
[0.430s]       sys.exit(main())
[0.430s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/main.py", line 53, in main
[0.430s]       abs_idl_file = convert_to_idl(
[0.430s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__init__.py", line 23, in convert_to_idl
[0.430s]       from rosidl_adapter.srv import convert_srv_to_idl
[0.430s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/srv/__init__.py", line 16, in <module>
[0.430s]       from rosidl_adapter.resource import expand_template
[0.430s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/resource/__init__.py", line 19, in <module>
[0.430s]       import em
[0.430s] 
[0.430s]   ModuleNotFoundError: No module named 'em'
[0.430s] 
[0.430s] Call Stack (most recent call first):
[0.430s]   /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
[0.430s]   CMakeLists.txt:17 (rosidl_generate_interfaces)
[0.430s] 
[0.430s] [0m
[0.430s] -- Configuring incomplete, errors occurred!
[0.430s] See also "/home/valtec/aether/aether_ws/build/aether_interfaces/CMakeFiles/CMakeOutput.log".
[0.433s] Invoked command in '/home/valtec/aether/aether_ws/build/aether_interfaces' returned '1': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/home/valtec/aether/aether_ws/install/aether_gcs_ui:/home/valtec/aether/aether_ws/install/aether_gcs_backend:/opt/ros/humble VIRTUAL_ENV_PROMPT=(.venv) /usr/bin/cmake /home/valtec/aether/aether_ws/src/aether_interfaces -DCMAKE_INSTALL_PREFIX=/home/valtec/aether/aether_ws/install/aether_interfaces
